name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: macos-latest
    
    steps:
    - uses: Teakowa/setup-serverless@v2.0.0
      with:
        provider: tencent
      env:
        TENCENT_APPID: ${{ secrets.TENCENT_APP_ID }}
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY}}
    - run: sls deploy
      
